// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/live-comm": {
    params: {};
  };
  "/charting-poc": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/health" | "/live-comm" | "/charting-poc";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/live-comm/_index.tsx": {
    id: "routes/live-comm/_index";
    page: "/live-comm";
  };
  "routes/charting-poc/_index.tsx": {
    id: "routes/charting-poc/_index";
    page: "/charting-poc";
  };
};